plugins {
    id("java")
}

group = "com"
version = "1.0.0"

repositories {
    mavenCentral()
    maven { url = uri("https://www.cursemaven.com") }
}

dependencies {
    compileOnly(files("${System.getProperty("user.home")}/AppData/Roaming/Hytale/install/release/package/game/latest/Server/HytaleServer.jar"))
    implementation("com.google.code.gson:gson:2.11.0")
    implementation("org.xerial:sqlite-jdbc:3.46.1.3")
    compileOnly(files("libs/OrbisGuard-0.8.3.jar"))
    compileOnly(files("libs/PlayerInteractLib-1.0.1.jar"))
    implementation("curse.maven:hyui-1431415:7693755")
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(configurations.runtimeClasspath.get().map { 
        if (it.isDirectory) it else zipTree(it) 
    })
}
tasks.register<Copy>("deployJar") {
    group = "run"
    description = "Copies the built JAR to build/runtimeMods to be used in the task generated by generateRuns"

    dependsOn(tasks.named("jar"))

    val runtimeModsDir = layout.buildDirectory.dir("runtimeMods").get().asFile

    doFirst {
        if (runtimeModsDir.exists()) {
            println("Cleaning old runtimeMods...")
            runtimeModsDir.deleteRecursively()
        }
        runtimeModsDir.mkdirs()
        
        layout.projectDirectory.dir("run").asFile.mkdirs()
    }

    from(tasks.named<Jar>("jar").flatMap { it.archiveFile }) {
        rename { it }
    }

    into(runtimeModsDir)

    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    doFirst {
        println("Deploying JAR to: ${runtimeModsDir.absolutePath}")
    }
}

tasks.register("generateRuns") {
    group = "run"
    description = "Generates an IntelliJ run configuration for Hytale Server"

    doFirst {
        layout.projectDirectory.dir("run").asFile.mkdirs()
    }

    doLast {
        val ideaDir = File(projectDir, ".idea/runConfigurations")
        if (!ideaDir.exists()) ideaDir.mkdirs()

        val runConfigFile = File(ideaDir, "Hytale_Server.xml")

        // Delete existing run configuration if it exists
        if (runConfigFile.exists()) {
            println("Deleting existing Hytale Server run configuration...")
            runConfigFile.delete()
        }

        runConfigFile.writeText("""
            <component name="ProjectRunConfigurationManager">
              <configuration default="false" name="Hytale Server" type="JarApplication">
                <option name="JAR_PATH" value="${'$'}USER_HOME$/AppData/Roaming/Hytale/install/release/package/game/latest/Server/HytaleServer.jar" />
                <option name="PROGRAM_PARAMETERS" value="--assets &quot;${'$'}USER_HOME$/AppData/Roaming/Hytale/install/release/package/game/latest/Assets.zip&quot; --mods &quot;${'$'}PROJECT_DIR$/build/runtimeMods&quot;" />
                <option name="WORKING_DIRECTORY" value="${'$'}PROJECT_DIR$/run" />
                <option name="ALTERNATIVE_JRE_PATH" />
                <method v="2">
                  <option name="Gradle.BeforeRunTask" enabled="true" tasks="deployJar" externalProjectPath="${'$'}PROJECT_DIR$" vmOptions="" scriptParameters="" />
                </method>
              </configuration>
            </component>
        """.trimIndent())

        println("Generated IntelliJ run configuration: ${runConfigFile.absolutePath}")
    }
}